apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 21.1.23
    - repoURL: 'https://github.com/vlad-panin/pub_repo.git'
      path: nginx
      targetRevision: main
      helm:
        valueFiles:
          - $values/nginx-values.yaml
    - repoURL: 'https://github.com/vlad-panin/pub_repo.git'
      targetRevision: main
      ref: values