apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: devops
  destination:
    server: https://kubernetes.default.svc
    namespace: devops
  sources:
    - repoURL: 'http://chartmuseum.devops.svc:8080'
      chart: nginx
      targetRevision: 15.6.1
      helm:
        valueFiles:
          - $values/nginx-values.yaml
    - repoURL: 'https://github.com/vlad-panin/pub_repo.git'
      targetRevision: main
      ref: values