apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  containers:
    - name: multitool
      image: curlimages/curl:latest
      command: ['sh', '-c', 'while true; do sleep 3600; done']
      imagePullPolicy: IfNotPresent
  restartPolicy: OnFailure
