apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-default
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nginx
    helm:
      parameters:
        - name: service.type
          value: ClusterIP
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 21.1.23
  syncPolicy:
    syncOptions:
      - CreateNamespace=true