service:
  type: ClusterIP
  ports:
    http: 8083

resources:
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPU: 100m
  targetMemory: 128Mi